# Generated by Django 4.1.12 on 2024-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afwg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='UserName',
            new_name='FacultyName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='MiddleName',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='FacultyIdNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
