# Generated by Django 4.1.12 on 2024-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afwg', '0002_rename_username_faculty_facultyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='DeloadUnit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
